package_assets: off
template_function: _.template
javascripts:
  app:
    - public/javascripts/jquery-1.6.2.min.js
    - public/javascripts/json2.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/application.js
    - public/javascripts/jquery.dotimeout.js
    - public/javascripts/models/*.js
    - public/javascripts/**/*.js
    - app/views/**/*.jst

stylesheets:
  app:
    - public/stylesheets/reset.css
    - public/stylesheets/*.css